### ISSUE TITLE
learn from Nsec

### ISSUE THREAD

**Issue by netpyoung** [netpyoung/unity.libsodium#5]
- [A modern and easy-to-use cryptographic library for .NET Core based on libsodium](https://github.com/ektrah/nsec)
- contribute?

**Comment by Verboton** [comment]
Hi,

Great little unity addon you did there!

Would it be easy to add bindings for PS4, XOne and Switch?

Also, is this binding of Sodium allowing to use sodium cpu instructions optims?

Regards,

**Comment by netpyoung** [comment]
close this issue. that need that test platform. so i close this issues
